server.port: 8080

spring:
  security:
    user:
      name: root
    password: root
    roles: admin
  datasource:
    url:  jdbc:mysql://localhost:8080/blogdb
    username: root
    password: 442211
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:

